name: Build, tests and docker

on: [push]

env:
  IMAGE_NAME: greeting-image

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Set up Java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'

      - name: Build without tests
        run: mvn package -DskipTests
      - name: Build and test
        run: mvn package
      - name: Build image in docker
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
             ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
             ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}